name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/reactjs-app .
      
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest

      # - name: Delete old container if it exists
      #   run: docker rm -f reactContainer || true

      - name: Restart old container if it exists
        run: docker restart reactContainer || true


      - name: Run Docker container
        run: docker run -d -p 3000:80 --name reactContainer ${{ secrets.DOCKER_USERNAME }}/reactjs-app:latest
